compressionLevel: mixed

enableGlobalCache: false

nodeLinker: node-modules

# fast-xml-parser 4.4.1 via @boxyhq/saml-jackson → @aws-sdk/core@3.816.0 (transitive).
# Only parses trusted AWS API responses, not user input. No practical attack vector.
# Upstream fix pending: ory/polis (saml-jackson) has bumped to @aws-sdk@3.994.0 on main but hasn't released yet.
npmAuditIgnoreAdvisories:
  - "1113407"

yarnPath: .yarn/releases/yarn-4.12.0.cjs
